# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mp4',
            field=models.FilePathField(blank=True, match='.*\\.mp4$', null=True, path='videos', recursive=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ogg',
            field=models.FilePathField(blank=True, match='.*\\.ogv$', null=True, path='videos', recursive=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='webm',
            field=models.FilePathField(blank=True, match='.*\\.webm$', null=True, path='videos', recursive=True),
        ),
    ]
