# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0002_auto_20180828_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.TournamentMatch')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournamentmatchplayer',
            name='tournamentplayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.TournamentPlayer'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='players',
            field=models.ManyToManyField(through='teamstats.TournamentMatchPlayer', to='teamstats.TournamentPlayer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(through='teamstats.TournamentPlayer', to='teamstats.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set([('tournament', 'player')]),
        ),
    ]
