# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0003_auto_20180829_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchplayer',
            name='tournamentplayer',
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
        migrations.DeleteModel(
            name='TournamentMatchPlayer',
        ),
    ]
