# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0004_auto_20180829_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.TournamentMatch')),
                ('tournamentplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.TournamentPlayer')),
            ],
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='players',
            field=models.ManyToManyField(through='teamstats.TournamentMatchPlayer', to='teamstats.TournamentPlayer'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.Tournament'),
        ),
    ]
