# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0005_auto_20180829_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('tournamentplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamstats.TournamentPlayer')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournamentmatchplayer',
            name='tournamentplayer',
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
        migrations.DeleteModel(
            name='TournamentMatchPlayer',
        ),
    ]
